Repository digitalisx/web-practice, pull requests merged in 2022-07, with the labels that each got.

#1 Feature/init
  hello.txt
  rur.txt
Labels: enhancement

#14 Add: 프로젝트 파일 및 폴더 정리
  README.md
  src/git/hello.txt
  src/git/rur.txt
  src/html/index.html
  src/svelte/App.svelte
Labels: enhancement

#18 Javascript: level1
  js-practice/filter_phoneNumber.js
  js-practice/middle_char.js
Labels: enhancement

#25 Fix: minor for javascript src path, `.gitignore`.
  .gitignore
  src/js/filter_phoneNumber.js
  src/js/middle_char.js
Labels: enhancement

#27 Javascript: File I/O with MBR Parser
  src/js/analyze.js
  src/js/mbr.html
Labels: good first issue

#31 HTML: `MBR` 분석 메인페이지 코드 위치 변경
  src/html/mbr.html
Labels: enhancement, good first issue
