Repository digitalisx/web-practice, pull requests merged in 2022-08, with the labels that each got.

#37 Vue: tutorial practice
  .gitignore
  src/vue/package-lock.json
  src/vue/package.json
  src/vue/vuedongsan/.gitignore
  src/vue/vuedongsan/README.md
  src/vue/vuedongsan/babel.config.js
  src/vue/vuedongsan/jsconfig.json
  src/vue/vuedongsan/package-lock.json
  src/vue/vuedongsan/package.json
  src/vue/vuedongsan/public/favicon.ico
  src/vue/vuedongsan/public/index.html
  src/vue/vuedongsan/src/App.vue
  src/vue/vuedongsan/src/assets/logo.png
  src/vue/vuedongsan/src/assets/oneroom.js
  src/vue/vuedongsan/src/assets/room0.jpg
  src/vue/vuedongsan/src/assets/room1.jpg
  src/vue/vuedongsan/src/assets/room2.jpg
  src/vue/vuedongsan/src/components/HelloWorld.vue
  src/vue/vuedongsan/src/main.js
  src/vue/vuedongsan/vue.config.js
Labels: good first issue

#38 Revert "Vue: tutorial practice"
  .gitignore
  src/vue/package-lock.json
  src/vue/package.json
  src/vue/vuedongsan/.gitignore
  src/vue/vuedongsan/README.md
  src/vue/vuedongsan/babel.config.js
  src/vue/vuedongsan/jsconfig.json
  src/vue/vuedongsan/package-lock.json
  src/vue/vuedongsan/package.json
  src/vue/vuedongsan/public/favicon.ico
  src/vue/vuedongsan/public/index.html
  src/vue/vuedongsan/src/App.vue
  src/vue/vuedongsan/src/assets/logo.png
  src/vue/vuedongsan/src/assets/oneroom.js
  src/vue/vuedongsan/src/assets/room0.jpg
  src/vue/vuedongsan/src/assets/room1.jpg
  src/vue/vuedongsan/src/assets/room2.jpg
  src/vue/vuedongsan/src/components/HelloWorld.vue
  src/vue/vuedongsan/src/main.js
  src/vue/vuedongsan/vue.config.js
Labels: bug

#39 Vue: tutorial practice
  .gitignore
  src/vue/package-lock.json
  src/vue/package.json
  src/vue/vuedongsan/.gitignore
  src/vue/vuedongsan/README.md
  src/vue/vuedongsan/babel.config.js
  src/vue/vuedongsan/jsconfig.json
  src/vue/vuedongsan/package-lock.json
  src/vue/vuedongsan/package.json
  src/vue/vuedongsan/public/favicon.ico
  src/vue/vuedongsan/public/index.html
  src/vue/vuedongsan/src/App.vue
  src/vue/vuedongsan/src/assets/logo.png
  src/vue/vuedongsan/src/assets/oneroom.js
  src/vue/vuedongsan/src/assets/room0.jpg
  src/vue/vuedongsan/src/assets/room1.jpg
  src/vue/vuedongsan/src/assets/room2.jpg
  src/vue/vuedongsan/src/main.js
  src/vue/vuedongsan/src/style.css
  src/vue/vuedongsan/vue.config.js
Labels: good first issue

#60 Vue: 본 Repo로 프로젝트 파일 옮기기
  src/vue/ajou/.editorconfig
  src/vue/ajou/.gitignore
  src/vue/ajou/.prettierrc
  src/vue/ajou/README.md
  src/vue/ajou/babel.config.js
  src/vue/ajou/jsconfig.json
  src/vue/ajou/package-lock.json
  src/vue/ajou/package.json
  src/vue/ajou/public/favicon.ico
  src/vue/ajou/public/index.html
  src/vue/ajou/src/App.vue
  src/vue/ajou/src/assets/logo.png
  src/vue/ajou/src/components/HelloWorld.vue
  src/vue/ajou/src/main.js
  src/vue/ajou/src/router/index.js
  src/vue/ajou/src/store/index.js
  src/vue/ajou/src/views/ClassView.vue
  src/vue/ajou/src/views/ContactView.vue
  src/vue/ajou/src/views/HomeView.vue
  src/vue/ajou/src/views/IntroductionView.vue
  src/vue/ajou/src/views/NewsView.vue
  src/vue/ajou/src/views/ProjectsView.vue
  src/vue/ajou/src/views/ResearchesView.vue
  src/vue/ajou/vue.config.js
  src/vue/package-lock.json
  src/vue/package.json
Labels: good first issue

#64 Vue: 웹 사이트 틀 제작하기
  src/vue/ajou/src/App.vue
  src/vue/ajou/src/assets/chitoh/e-비즈니스학과.jpg
  src/vue/ajou/src/assets/chitoh/간호학과.jpg
  src/vue/ajou/src/assets/chitoh/건설시스템공학과.jpg
  src/vue/ajou/src/assets/chitoh/건축학과.jpg
  src/vue/ajou/src/assets/chitoh/경영학과.jpg
  src/vue/ajou/src/assets/chitoh/경제학과.jpg
  src/vue/ajou/src/assets/chitoh/교통시스템공학과.jpg
  src/vue/ajou/src/assets/chitoh/국방디지털융합학과.jpg
  src/vue/ajou/src/assets/chitoh/국어국문학과.jpg
  src/vue/ajou/src/assets/chitoh/금융공학과.jpg
  src/vue/ajou/src/assets/chitoh/기계공학과.jpg
  src/vue/ajou/src/assets/chitoh/문화콘텐츠학과.jpg
  src/vue/ajou/src/assets/chitoh/물리학과.jpg
  src/vue/ajou/src/assets/chitoh/미디어학과.jpg
  src/vue/ajou/src/assets/chitoh/불어불문학과.jpg
  src/vue/ajou/src/assets/chitoh/사이버보안학과.jpg
  src/vue/ajou/src/assets/chitoh/사학과.jpg
  src/vue/ajou/src/assets/chitoh/사회학과.jpg
  src/vue/ajou/src/assets/chitoh/산업공학과.jpg
  src/vue/ajou/src/assets/chitoh/생명과학과.jpg
  src/vue/ajou/src/assets/chitoh/소프트웨어학과.jpg
  src/vue/ajou/src/assets/chitoh/수학과.jpg
  src/vue/ajou/src/assets/chitoh/스포츠레저학과.jpg
  src/vue/ajou/src/assets/chitoh/신소재공학과.jpg
  src/vue/ajou/src/assets/chitoh/심리학과.jpg
  src/vue/ajou/src/assets/chitoh/약학과.jpg
  src/vue/ajou/src/assets/chitoh/영어영문학과.jpg
  src/vue/ajou/src/assets/chitoh/응용화학생명공학과.jpg
  src/vue/ajou/src/assets/chitoh/의학과.jpg
  src/vue/ajou/src/assets/chitoh/인공지능융합학과.jpg
  src/vue/ajou/src/assets/chitoh/전자공학과.jpg
  src/vue/ajou/src/assets/chitoh/정치외교학과.jpg
  src/vue/ajou/src/assets/chitoh/행정학과.jpg
  src/vue/ajou/src/assets/chitoh/화학공학과.jpg
  src/vue/ajou/src/assets/chitoh/화학과.jpg
  src/vue/ajou/src/assets/chitoh/환경안전공학과.jpg
  src/vue/ajou/src/assets/colleges.js
  src/vue/ajou/src/assets/logo.png
  src/vue/ajou/src/components/CollegeCategory.vue
  src/vue/ajou/src/components/DepartmentSelect.vue
  src/vue/ajou/src/components/HelloWorld.vue
  src/vue/ajou/src/components/main.css
  src/vue/ajou/src/router/index.js
  src/vue/ajou/src/views/CatView.vue
  src/vue/ajou/src/views/ClassView.vue
  src/vue/ajou/src/views/CollegeView.vue
  src/vue/ajou/src/views/HomeView.vue
  src/vue/ajou/src/views/IntroductionView.vue
  src/vue/ajou/src/views/ProjectsView.vue
  src/vue/ajou/src/views/colleges/BusinessView.vue
  src/vue/ajou/src/views/colleges/EngineeringView.vue
  src/vue/ajou/src/views/colleges/HumanitiesView.vue
  src/vue/ajou/src/views/colleges/InformationCommunicationView.vue
  src/vue/ajou/src/views/colleges/MedicineView.vue
  src/vue/ajou/src/views/colleges/NaturalScienceView.vue
  src/vue/ajou/src/views/colleges/NursingView.vue
  src/vue/ajou/src/views/colleges/PharmacyView.vue
  src/vue/ajou/src/views/colleges/SocialScienceView.vue
  src/vue/ajou/src/views/colleges/SoftwareFusionView.vue
Labels: enhancement

#70 Vue: dynamic carousel slide.
  src/vue/ajou/src/assets/home/univ1.jpg
  src/vue/ajou/src/assets/home/univ2.jpg
  src/vue/ajou/src/assets/home/univ3.jpg
  src/vue/ajou/src/views/HomeView.vue
Labels: enhancement

#69 Vue: home image carousel slide
  src/vue/ajou/package-lock.json
  src/vue/ajou/package.json
  src/vue/ajou/src/assets/home/univ1.jpg
  src/vue/ajou/src/assets/home/univ2.jpg
  src/vue/ajou/src/assets/home/univ3.jpg
  src/vue/ajou/src/views/CollegeView.vue
  src/vue/ajou/src/views/HomeView.vue
  src/vue/ajou/vue.config.js
  src/vue/ajou/yarn.lock
Labels: enhancement
